apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: remote-ssh-commands
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: ssh, ssh remote
    tekton.dev/displayName: "ssh remote commands"
spec:
  workspaces:
    - name: credentials
  params:
    - name: HOST
      type: string
    - name: USERNAME
      type: string
    - name: PORT
      type: string
      default: "22"
    - name: SSH_SCRIPT
      type: string
    - name: USE_INSECURE_CIPHER
      type: string
      default: "false"
  steps:
    - name: ssh
      image: docker.io/appleboy/drone-ssh:1.6.1@sha256:8252f5232316d832e14f259ed7b217d8d5f620d4668419d88ed47e1a48c0896a #tag: 1.6.1
      workingDir: $(workspaces.credentials.path)
      script: |

        export script="$(params.SSH_SCRIPT)"
        cmd=""
        [[ -f ./privatekey ]] && cmd="$cmd -i ./privatekey"
        [[ -f ./password ]] && cmd="$cmd -P $(cat ./password)"
        [[ -f ./passphrase ]] && cmd="$cmd --ssh-passphrase $(cat ./passphrase)"
        [[ -f ./ciphers ]] && cmd="$cmd --ciphers $(cat ./ciphers)"
        [[ $(params.USE_INSECURE_CIPHER) == "true" ]] && cmd="$cmd --useInsecureCipher true"

        drone-ssh -H $(params.HOST) -p $(params.PORT) -u $(params.USERNAME) -s "$script" $cmd
