apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: remote-ssh-commands-run
spec:
  taskRef:
    name: remote-ssh-commands
  workspaces:
    - name: credentials
      secret:
        secretName: remote-ssh-secret
  params:
    - name: HOST
      value: "ip-address-of-remote-x86_64-vm"
    - name: USERNAME
      value: "root"
    - name: SSH_SCRIPT
      value: |
        dnf install podman buildah -y
        sudo podman run --rm --privileged multiarch/qemu-user-static --reset -p yes
        rm -rf ppc64le-dockerfile
        git clone https://github.com/mayurwaghmode/ppc64le-dockerfile.git
        cd /root/ppc64le-dockerfile/
        buildah bud -f Dockerfile -t ppc64le-container .
        buildah from localhost/ppc64le-container
        buildah commit ppc64le-container-working-container ppc64le-container
        buildah login -u Quay-User-Name -p Quay-Password quay.io
        buildah push ppc64le-container quay.io/Quay-User-Name/Quay-Repository-Name
