apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: remote-ssh-commands-run
spec:
  taskRef:
    name: remote-ssh-commands
  workspaces:
    - name: credentials
      secret:
        secretName: remote-ssh-secret
  params:
    - name: HOST
      value: "169.63.181.242"
    - name: USERNAME
      value: "root"
    - name: SSH_SCRIPT
      value: |
        dnf install podman buildah -y
        sudo podman run --rm --privileged multiarch/qemu-user-static --reset -p yes
        rm -rf tekton-taskrun
        git clone https://github.com/mayurwaghmode/tekton-taskrun.git
        cd /root/tekton-taskrun/
        buildah bud -f Dockerfile -t ppc64le-container .
        buildah from localhost/ppc64le-container
        buildah commit ppc64le-container-working-container ppc64le-container
        buildah login docker.io 
        buildah push ppc64le-container mwaghmodepersistent/ppc64le-container
